services:
  speaches:
    container_name: speaches
    build:
      dockerfile: Dockerfile
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - WHISPER__MODEL_INSTANCES_PER_MODEL=4
      - WHISPER__MAX_CONCURRENT_JOBS=4
      - WHISPER__ENABLE_CPU_AFFINITY=true
      - WHISPER__USE_PROCESS_POOL=true
      # Threading environment fixes
      - OMP_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - NUMBA_NUM_THREADS=1
    develop:
      watch:
        - action: rebuild
          path: ./uv.lock
        - action: sync+restart
          path: ./src
          target: /home/ubuntu/speaches/src
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://0.0.0.0:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
