[project]
name = "faster-whisper-server"
requires-python = ">=3.12,<3.13"
dependencies = [
    "pydantic",
    "fastapi",
    "uvicorn",
    "python-multipart",
    "soundfile",
    "pydantic-settings",
    "numpy",
    "faster-whisper",
    "huggingface-hub",
    "httpx-sse",
    "httpx",
    "gradio",
]

[project.optional-dependencies]
dev = ["ruff", "pytest", "pytest-xdist"]
other = ["youtube-dl@git+https://github.com/ytdl-org/youtube-dl.git", "openai", "aider-chat"]

[tool.ruff]
target-version = "py312"

[tool.pyright]
# typeCheckingMode = "strict"
pythonVersion = "3.12"
pythonPlatform = "Linux"
# https://github.com/RobertCraigie/pyright-python/tree/804dafbe7ab1b9c8766c2b4755fb29db37959ab7?tab=readme-ov-file#pre-commit
venvPath = "."
venv = ".venv"
